title: Down The Sun Goes
description: Dumb comics and blogs by Machary / PigCart
url: https://downthesungoes.com
    
# Build settings
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      firstcomic: "/conclusion/"
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
      
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - view-site.bat
